/**
 * The API origin this build talks to.
 *
 * Regenerated by frontend/scripts/write-backend-origin.js on every build, from
 * the BACKEND_ORIGIN environment variable. The value below is the committed
 * default and is what a build without that variable produces, so the file is
 * checked in rather than generated from nothing — a missing variable must not
 * be able to produce a bundle that points at no API at all.
 *
 * Set BACKEND_ORIGIN in the hosting provider (Vercel project settings, Render
 * service environment) to point a deployment at a different API, for example
 * the Render service that hosts this backend.
 */
export const PRODUCTION_BACKEND_ORIGIN = 'https://api.ligibet.site';
